version: '3.8'

services:
  # Contenedor MongoDB
  mongodb:
    image: mongo:7.0
    container_name: caso4_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: peliculas_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - mongodb_network

  # Contenedor mongo-express (Herramienta de administración web)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: caso4_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - mongodb_network

  # Contenedor Python para desarrollo
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caso4_python_app
    restart: always
    volumes:
      - .:/app
      - /app/venv
    working_dir: /app
    environment:
      - MONGODB_URL=mongodb://admin:admin123@mongodb:27017/peliculas_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
